services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./gutenberg-custom-blocks:/var/www/html/wp-content/plugins
      - ./zacks-test-child-theme:/var/www/html/wp-content/themes/zacks-test-child-theme

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:20
    working_dir: /app
    volumes:
      - ./gutenberg-custom-blocks:/app
    command: tail -f /dev/null

volumes:
  wordpress_data:
  db_data:
